# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

hashbang() {
	ssh sapeint@da1.hashbang.sh
}

alias activate="source venv/bin/activate"
