# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

hashbang() {
	ssh sapeint@da1.hashbang.sh
}

alias activate="source venv/bin/activate"
alias coderadio="mpv --input-ipc-server=${XDG_RUNTIME_DIR}/mpvsocket  --stream-lavf-o=reconnect_streamed=1 https://coderadio-admin.freecodecamp.org/radio/8010/radio.mp3"
alias cr=coderadio
